---

- name: MailCow | Showing debug info - user provided config
  ansible.builtin.debug:
    var: mailcow
  when: debug | bool

- name: MailCow | Showing debug info - running config
  ansible.builtin.debug:
    var: MC_CONFIG
  when: debug | bool

- name: MailCow | Checking config
  ansible.builtin.assert:
    that:
      - mailcow is defined
      - "ansible_virtualization_role is undefined or ansible_virtualization_role != 'guest' or 'docker' not in ansible_virtualization_tech_guest"
      - MC_CONFIG.fqdn
      - MC_CONFIG.fqdn | valid_hostname
  tags: always

- name: MailCow | Checking config for Nginx
  ansible.builtin.assert:
    that:
      - MC_CONFIG.config.HTTP_PORT | int != MC_CONFIG.nginx.port_plain | int
      - MC_CONFIG.config.HTTPS_PORT | int != MC_CONFIG.nginx.port_ssl | int
  when: MC_CONFIG.manage.webserver | bool
  tags: always

- name: MailCow | Processing debian config
  ansible.builtin.import_tasks: debian/main.yml
  when: "ansible_distribution|lower in ['debian', 'ubuntu']"
